nome = input('Digite algo: ')
print('O tipo primitivo desse valor é', type(nome))
print('Só tem espaços?', nome.isspace())
print('E numero?', nome.isnumeric())
print('É alfabetico?', nome.isalpha())
print('É alfanumerico?', nome.isalnum())
print('Está em maiusculas?', nome.isupper())
print('Está em minusculas?', nome.islower())
print('Está capitalizada?', nome.istitle())